[package]
name = "bls48581"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "staticlib"]
name = "bls48581"

[dependencies]
hex = "0.4.3"
serde_json = "1.0.117"
uniffi = {  version= "0.25", features = ["cli"]}

[build-dependencies]
uniffi = { version = "0.25", features = [ "build" ] }