version: "3.8"

name: quilibrium

# See sysctl related warning in DOCKER-README.md.
# Host configuration changes are required.

services:
  node:
    build: ./
    image: quilibrium
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 32G
        reservations:
          cpus: 12
          memory: 16G
    environment:
      - DEFAULT_LISTEN_GRPC_MULTIADDR=/ip4/0.0.0.0/tcp/8337
      - DEFAULT_LISTEN_REST_MULTIADDR=/ip4/0.0.0.0/tcp/8338
      - DEFAULT_STATS_MULTIADDR=/dns/stats.quilibrium.com/tcp/443
    ports:
      - '8336:8336/udp' # p2p
      - '127.0.0.1:8337:8337/tcp' # gRPC
      - '127.0.0.1:8338:8338/tcp' # REST
    healthcheck:
      test: ["CMD", "node", "--peer-id"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 1m
    volumes:
      - ./.config:/opt/ceremonyclient/node/.config
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 2048m
