# https://taskfile.dev

version: '3'

dotenv:
  - '.env'

vars:
  VERSION:
    sh: cat node/main.go | grep "Quilibrium Node - v" |  grep -Eo '[0-9]+\.[0-9]+\.[0-9]+'
  SERVICE_NAME: node
  GIT_REPO:
    sh: git config --get remote.origin.url
  GIT_BRANCH:
    sh: git rev-parse --abbrev-ref HEAD
  GIT_COMMIT:
    sh: git log -1 --format=%h

tasks:
  status:
    desc: Display configuration info.
    cmds:
      - echo -n "Image name:" && echo " ${QUILIBRIUM_IMAGE_NAME:-quilibrium}"
      - echo -n "Version   :" && echo " {{.VERSION}}"
      - echo -n "Repo      :" && echo " {{.GIT_REPO}}"
      - echo -n "Branch    :" && echo " {{.GIT_BRANCH}}"
      - echo -n "Commit    :" && echo " {{.GIT_COMMIT}}"
    silent: true

  build:
    desc: Build the Quilibrium docker image, unless it is already built.
    cmds:
      - |
        docker build \
        --build-arg GIT_REPO={{.GIT_REPO}} \
        --build-arg GIT_BRANCH={{.GIT_BRANCH}} \
        --build-arg GIT_COMMIT={{.GIT_COMMIT}} \
        -t ${QUILIBRIUM_IMAGE_NAME:-quilibrium}:{{.VERSION}} \
        -t ${QUILIBRIUM_IMAGE_NAME:-quilibrium}:latest \
        .
    status:
      - |
        docker image inspect \
        ${QUILIBRIUM_IMAGE_NAME:-quilibrium}:{{.VERSION}} \
        >/dev/null 2>/dev/null

  up:
    desc: Run a new Quilibrium container, through docker compose.
    cmds:
      - docker compose up -d

  down:
    desc: Take down the Quilibrium container, through docker compose.
    cmds:
      - docker compose down

  shell:
    desc: Drop into a shell inside the running container.
    cmds:
      - docker compose exec -it {{.SERVICE_NAME}} sh

  logs:
    desc: Print the logs of the running Quilibrium container.
    cmds:
      - docker compose logs

  backup:
    desc: Create a backup file with the critical configuration files.
    sources:
      - '.config/config.yml'
      - '.config/keys.yml'
    cmds:
      - |
        export TMP_DIR=$(mktemp -d)
        export TASK_DIR=$(pwd)
        echo $TMP_DIR
        sudo cp .config/config.yml $TMP_DIR
        sudo cp .config/keys.yml $TMP_DIR
        sudo chown $(whoami):$(id -gn) $TMP_DIR/*
        cd $TMP_DIR
        tar -cvzf $TASK_DIR/backup.tar.gz *
        cd $TASK_DIR
        sudo rm -rf $TMP_DIR

  github:login:
    desc: Login to GitHub container registry.
    cmds:
      - echo $GITHUB_TOKEN | docker login ghcr.io -u $GITHUB_USERNAME --password-stdin

  push:
    desc: Push Quilibrium docker image to the container registry.
    cmds:
      - docker push ${QUILIBRIUM_IMAGE_NAME:-quilibrium}:{{.VERSION}}
      - docker push ${QUILIBRIUM_IMAGE_NAME:-quilibrium}:latest
