# https://taskfile.dev

version: '3'

dotenv:
  - '.env'

vars:
  PROJECT_NAME: quilibrium
  SERVICE_NAME: node

tasks:
  up:
    desc: Run a new Quilibrium container, through docker compose.
    cmds:
      - docker compose up -d

  down:
    desc: Take down the Quilibrium container, through docker compose.
    cmds:
      - docker compose down

  shell:
    desc: Drop into a shell inside the running container.
    cmds:
      - docker compose exec -it {{.SERVICE_NAME}} sh

  logs:
    desc: Print the logs of the running Quilibrium container.
    cmds:
      - docker compose logs -f

  logs-folder:
    desc: Show where Docker stores the logs for the Quilibrium node. You need root permissions to access the folder.
    cmds:
      - "docker container inspect {{.PROJECT_NAME}}-{{.SERVICE_NAME}}-1 | grep LogPath | cut -d : -f 2 | cut -d '\"' -f 2 | xargs dirname"

  node-info:
    desc: Displays node related info for a running node.
    cmds:
      - docker compose exec node node -node-info

  backup:
    desc: Create a backup file with the critical configuration files.
    prompt: You will be prompted for root access. Make sure you verify the generated backup file. Continue?
    sources:
      - '.config/config.yml'
      - '.config/keys.yml'
    outputs:
      - 'backup.tar.gz'
    cmds:
      - |
        export TMP_DIR=$(mktemp -d)
        export TASK_DIR=$(pwd)
        sudo cp .config/config.yml $TMP_DIR
        sudo cp .config/keys.yml $TMP_DIR
        sudo chown $(whoami):$(id -gn) $TMP_DIR/*
        cd $TMP_DIR
        tar -czf $TASK_DIR/backup.tar.gz *
        cd $TASK_DIR
        sudo rm -rf $TMP_DIR
        echo "Backup saved to: backup.tar.gz"
        echo "Do not assume you have a backup unless you verify it!!!"
    silent: true
